version: '3.2'
services: 
  cypress:
    image: "cypress/included:6.4.0"
    environment:
      - CYPRESS_baseUrl=https://portal-prtlshared.devint.superchoice.com.au
    working_dir: /e2e
    volumes:
      - ./:/e2e